<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>Zeitlind.Hook.Hsr</AssemblyName>
    <RootNamespace>Zeitlind.Hook.Hsr</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <NativeLib>Shared</NativeLib>
    <InvariantGlobalization>true</InvariantGlobalization>
    <OptimizationPreference>Speed</OptimizationPreference>
    <DebugSymbols>false</DebugSymbols>
    <DebugType>none</DebugType>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.DisableRuntimeMarshallingAttribute" />
    <ProjectReference Include="..\Zeitlind.Hook.Common\Zeitlind.Hook.Common.csproj" />
  </ItemGroup>
</Project>
